services:
  - type: web
    name: croptube
    runtime: docker
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: croptube-storage
      mountPath: /app/bin
      sizeGB: 1
